### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by random1167** [cyberpwnn/React#21]
if something like below was to make more lag then prevent it,please ignore my stupidity XD.
___________
Hello,would you be able to inplement a way for us to limit spawners and spawner delays thus allow us to make some spawners more valuable then others ?
or if you know of such a plugin that dose this?
currently im using these settings to help stop mass amounts of spawns
``` YAML
action-cull-entities:
  enable-entity-spawn-radius: true
  max-entities-radius: 16
  max-entities-per-chunk: 16
component:
  enable: true
  interval: 25
```

**Comment by cyberpwnn** [comment]
Try this 

``` YAML
action-cull-entities:
  enable-entity-spawn-radius: true
  max-entities-radius: 4
  max-entities-per-chunk: 18
  max-entities-per-radius: 6
component:
  enable: true
  interval: 100
  cullable:
  - EXPERIENCE_ORB
  - LEASH_HITCH
  - SNOWBALL
  - FIREBALL
  - SMALL_FIREBALL
  - PRIMED_TNT
  - FALLING_BLOCK
  - FIREWORK
  - ARMOR_STAND
  - MINECART_COMMAND
  - MINECART
  - MINECART_CHEST
  - MINECART_FURNACE
  - MINECART_TNT
  - MINECART_HOPPER
  - MINECART_MOB_SPAWNER
  - CREEPER
  - SKELETON
  - SPIDER
  - GIANT
  - ZOMBIE
  - SLIME
  - GHAST
  - PIG_ZOMBIE
  - ENDERMAN
  - CAVE_SPIDER
  - SILVERFISH
  - BLAZE
  - MAGMA_CUBE
  - ENDER_DRAGON
  - WITHER
  - BAT
  - WITCH
  - ENDERMITE
  - GUARDIAN
  - PIG
  - SHEEP
  - COW
  - CHICKEN
  - SQUID
  - WOLF
  - MUSHROOM_COW
  - SNOWMAN
  - OCELOT
  - IRON_GOLEM
  - HORSE
  - RABBIT
  - VILLAGER
  - SPLASH_POTION
  - FISHING_HOOK
```
